//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SK.Visit.UI.Blazor.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VisitTextRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VisitTextRessources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SK.Visit.UI.Blazor.Resources.VisitTextRessources", typeof(VisitTextRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Completed.
        /// </summary>
        public static string currentTrip_Completed_Message {
            get {
                return ResourceManager.GetString("currentTrip_Completed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are no trips scheduled for today. Please check back later or tomorrow..
        /// </summary>
        public static string currentTrip_NoTrip_Message {
            get {
                return ResourceManager.GetString("currentTrip_NoTrip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Today&apos;s Trip.
        /// </summary>
        public static string currentTrip_PageTitle {
            get {
                return ResourceManager.GetString("currentTrip_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause Trip.
        /// </summary>
        public static string currentTrip_PauseTrip_Button {
            get {
                return ResourceManager.GetString("currentTrip_PauseTrip_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click (Pause Trip) above to Pause your trip for today..
        /// </summary>
        public static string currentTrip_PauseTrip_Message {
            get {
                return ResourceManager.GetString("currentTrip_PauseTrip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resume Trip.
        /// </summary>
        public static string currentTrip_ResumeTrip_Button {
            get {
                return ResourceManager.GetString("currentTrip_ResumeTrip_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click (Resume Trip) above to resume your trip for today..
        /// </summary>
        public static string currentTrip_ResumeTrip_Message {
            get {
                return ResourceManager.GetString("currentTrip_ResumeTrip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Trip.
        /// </summary>
        public static string currentTrip_StartTrip_Button {
            get {
                return ResourceManager.GetString("currentTrip_StartTrip_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click (Start Trip) above to begin your trip for today..
        /// </summary>
        public static string currentTrip_StartTrip_Message {
            get {
                return ResourceManager.GetString("currentTrip_StartTrip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All of today&apos;s trips have been completed. Great job!.
        /// </summary>
        public static string currentTrip_TripCompleted_Message {
            get {
                return ResourceManager.GetString("currentTrip_TripCompleted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrival.
        /// </summary>
        public static string DisplayDestinations_Arrival {
            get {
                return ResourceManager.GetString("DisplayDestinations_Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish.
        /// </summary>
        public static string DisplayDestinations_Finish {
            get {
                return ResourceManager.GetString("DisplayDestinations_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note.
        /// </summary>
        public static string DisplayDestinations_Note {
            get {
                return ResourceManager.GetString("DisplayDestinations_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous Notes.
        /// </summary>
        public static string DisplayDestinations_PreviousNote {
            get {
                return ResourceManager.GetString("DisplayDestinations_PreviousNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skip Reason.
        /// </summary>
        public static string DisplayDestinations_SkipReason {
            get {
                return ResourceManager.GetString("DisplayDestinations_SkipReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string DisplayDestinations_Status {
            get {
                return ResourceManager.GetString("DisplayDestinations_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Today&apos;s Destinations.
        /// </summary>
        public static string DisplayDestinations_TodayDestinations_Title {
            get {
                return ResourceManager.GetString("DisplayDestinations_TodayDestinations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Arrived at.
        /// </summary>
        public static string TripStep__ArrivedAt_Text {
            get {
                return ResourceManager.GetString("TripStep_ ArrivedAt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Additional note.
        /// </summary>
        public static string TripStep_AdditionalNote_Text {
            get {
                return ResourceManager.GetString("TripStep_AdditionalNote_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete visit &amp; continue.
        /// </summary>
        public static string TripStep_CompleteAndContinue_Button {
            get {
                return ResourceManager.GetString("TripStep_CompleteAndContinue_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current Destination.
        /// </summary>
        public static string TripStep_CurrentDestination {
            get {
                return ResourceManager.GetString("TripStep_CurrentDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mark Arrival.
        /// </summary>
        public static string TripStep_MarkArrival_Button {
            get {
                return ResourceManager.GetString("TripStep_MarkArrival_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note.
        /// </summary>
        public static string TripStep_Note_Text {
            get {
                return ResourceManager.GetString("TripStep_Note_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à optional.
        /// </summary>
        public static string TripStep_optional_Text {
            get {
                return ResourceManager.GetString("TripStep_optional_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous Notes.
        /// </summary>
        public static string TripStep_PreviousNote {
            get {
                return ResourceManager.GetString("TripStep_PreviousNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reason for skipping the visit.
        /// </summary>
        public static string TripStep_ReasonForSkip_Text {
            get {
                return ResourceManager.GetString("TripStep_ReasonForSkip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save &amp; Next trip.
        /// </summary>
        public static string TripStep_SaveAndNext_Button {
            get {
                return ResourceManager.GetString("TripStep_SaveAndNext_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a reason....
        /// </summary>
        public static string TripStep_SelectAReason_Select {
            get {
                return ResourceManager.GetString("TripStep_SelectAReason_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skip Permanently.
        /// </summary>
        public static string TripStep_SkipPermanently_Button {
            get {
                return ResourceManager.GetString("TripStep_SkipPermanently_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skip Temporary.
        /// </summary>
        public static string TripStep_SkipTemporary_Button {
            get {
                return ResourceManager.GetString("TripStep_SkipTemporary_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Write your note here....
        /// </summary>
        public static string TripStep_WriteYourNote_Text {
            get {
                return ResourceManager.GetString("TripStep_WriteYourNote_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visits &amp; Deliveries.
        /// </summary>
        public static string visitMenu_MenuTitle {
            get {
                return ResourceManager.GetString("visitMenu_MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Schedule.
        /// </summary>
        public static string visitMenu_MenuTitle_Schedule {
            get {
                return ResourceManager.GetString("visitMenu_MenuTitle_Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trips.
        /// </summary>
        public static string visitMenu_MenuTitle_Trips {
            get {
                return ResourceManager.GetString("visitMenu_MenuTitle_Trips", resourceCulture);
            }
        }
    }
}
