name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore ./SK.Solution.sln
        
      - name: Build
        run: dotnet build ./SK.Solution.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./SK.Solution.sln --configuration Release --no-build --output ./publish

      - name: Copy files to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_PASSWORD }} # use 'password' instead if needed
          port: 22
          source: "./publish/*"
          target: "C:/inetpub/wwwroot/myapp" # adjust to your destination folder
        
      
