name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore ./SK.Solution.sln
        
      - name: Build
        run: dotnet build ./SK.Solution.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./SK.Solution.sln --configuration Release --no-build --output ./publish

      - name: Copy files to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          port: 22
          source: "publish/." 
          target: "C:/inetpub/wwwroot/sksolutiondeplyed" # adjust to your destination folder

      - name: Restart IIS App Pool
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          port: 22
          script: |
            powershell -Command "Import-Module WebAdministration; Restart-WebAppPool 'DefaultAppPool'"
        
      
