name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore ./SK.Solution.sln
        
      - name: Build
        run: dotnet build ./SK.Solution.sln --configuration Release --no-restore

      - name: Test
        run: |
          for proj in $(find . -name '*.Tests.csproj'); do
          echo "Running tests in $proj"
          dotnet test "$proj" --configuration Release --no-build --logger trx
          done

      - name: Publish
        run: dotnet publish ./SK.Solution.sln --configuration Release --no-build
